User.create(:username => "ColoradoGuy", :password => "mountains")
User.create(:username => "apple_3.14159", :password => "pie")
User.create(:username => "hippiedude", :password => "peace")
User.create(:username => "Noshaveforever", :password => "hair")
User.create(:username => "dirtbiker", :password => "muddy")

Plan.create(:location => "yellowstone", :party_number => 6, :shelter_type => "tent", :user_id => 1)
Plan.create(:location => "sedona", :party_number => 4, :shelter_type => "hammock", :user_id => 2)
Plan.create(:location => "bend", :party_number => 3, :shelter_type => "tent", :user_id => 3)
Plan.create(:location => "flagstaff", :party_number => 2, :shelter_type => "trailor", :user_id => 4)
Plan.create(:location => "pine", :party_number => 6, :shelter_type => "trailor", :user_id => 1)
Plan.create(:location => "grand lake", :party_number => 1, :shelter_type => "under the stars", :user_id => 2)
Plan.create(:location => "sylvan", :party_number => 6, :shelter_type => "tent", :user_id => 3)
Plan.create(:location => "moon", :party_number => 2, :shelter_type => "rocket ship", :user_id => 4)
Plan.create(:location => "mountains", :party_number => 12, :shelter_type => "cabin", :user_id => 1)
