User.create(username: "ColoradoGuy", password: "mountains")
User.create(username: "apple_3.14159", password: "pie")
User.create(username: "hippiedude", password: "peace")
User.create(username: "Noshaveforever", password: "hair")
User.create(username: "dirtbiker", password: "muddy")

Plan.create(location: "Yellowstone", party_number: 6, shelter_type: "tent", user_id: 1)
Plan.create(location: "Sedona", party_number: 4, shelter_type: "hammock", user_id: 2)
Plan.create(location: "Bend", party_number: 3, shelter_type: "tent", user_id: 3)
Plan.create(location: "Flagstaff", party_number: 2, shelter_type: "trailor", user_id: 4)
Plan.create(location: "Pine", party_number: 6, shelter_type: "trailor", user_id: 1)
Plan.create(location: "Grand Lake", party_number: 1, shelter_type: "under the stars", user_id: 2)
Plan.create(location: "Sylvan", party_number: 6, shelter_type: "tent", user_id: 3)
Plan.create(location: "Moon", party_number: 2, shelter_type: "rocket ship", user_id: 4)
Plan.create(location: "Mountains", party_number: 12, shelter_type: "cabin", user_id: 1)
